### ISSUE TITLE
Release 0.1 Checklist

### ISSUE THREAD

**Issue by danmelton** [hackoregon/openelections#532]
This is a complete walk through of the application. When we do a release, start a new release, and title it with the release version

First, reseed the database before running a complete check.

### As a GovAdmin, I can:

- [x] login with email govadmin@openelectionsportland.org and password of password
- [x] can access /campaigns
- [x] Add a new campaign and a campaign admin user at the same time

### As a campaign admin, I can

- [x] Receives email notification of invite to join from government admin
- [x] Accepts invite and add a password
- [x] login with new password
- [x] cannot access /campaigns
- [x] access my campaign /dashboard
- [x] access /manage-portal
- [x] add a new user 
- [x] access Manage User 'profile' page
- [x] remove a user
- [x] resend and invite

### As a new campaign staff, I can

- [x] Receive invitation email and sign up with a password
- [x] access the /manage-portal but not see any add new user or manage user buttons

### As any logged in User, I can:

- [x] log out
- [x] access reset my password from dashboard and successfully change my password
- [x] log in with my changed password
- [x] From sign in screen, request a password reset
- [x] I receive a password reset email, and can submit an updated password
- [x] log in with my reset password
