### ISSUE TITLE
City - User Acceptance Release Checklist 0.1

### ISSUE THREAD

**Issue by danmelton** [hackoregon/openelections#567]
This is a complete walk through of the application. When we do a release, start a new release, and title it with the release version

First, reseed the database before running a complete check.

### As a GovAdmin, I can:

- [x] login with email govadmin@openelectionsportland.org and password of password
- [x] can access /campaigns
- [x] Add a new campaign and a campaign admin user at the same time

### As a campaign admin, I can

- [x] Receives email notification of invite to join from government admin
- [x] Accepts invite and add a password
- [x] login with new password
- [x] cannot access /campaigns
- [x] access my campaign /dashboard
- [x] access /manage-portal
- [x] add a new user 
- [x] access Manage User 'profile' page
- [x] remove a user
- [x] resend an invite

### As a new campaign staff, I can

- [x] Receive invitation email and sign up with a password
- [x] access the /manage-portal but not see any add new user or manage user buttons

### As any logged in User, I can:

- [x] log out
- [x] access reset my password from dashboard and successfully change my password
- [x] log in with my changed password
- [x] From sign in screen, request a password reset
- [x] I receive a password reset email, and can submit an updated password
- [x] log in with my reset password

**Comment by danmelton** [comment]
I could not remove a user as a new campaign admin, it gave me an error

![Cursor_and_Open_Elections](https://user-images.githubusercontent.com/99731/62505324-0e636480-b7b1-11e9-9be9-056f2a290e50.png)

**Comment by danmelton** [comment]
> I could not remove a user as a new campaign admin, it gave me an error
> 
> ![Cursor_and_Open_Elections](https://user-images.githubusercontent.com/99731/62505324-0e636480-b7b1-11e9-9be9-056f2a290e50.png)

Issue fixed by #570

**Comment by susanmottet** [comment]
When I sign in as a campaign and go to /campaigns, it is good that the campaign can't see other campaign users, but it is problematic that a campaign has an "add a new campaign" button. Only a City user should be able to add new campaigns. 

![image](https://user-images.githubusercontent.com/48932344/62660912-4dfe8d80-b924-11e9-95db-5d64a45783e3.png)

**Comment by susanmottet** [comment]
Question: How can I as a government user, add a new government user?

**Comment by susanmottet** [comment]
Can we change the email to new campaigns/users in the following ways:
-Sender named something like "OpenElections"
-Add the text "The Open & Accountable Elections program is inviting you to sign up for its campaign finance reporting and data analysis app." so folks know that this email is about the OAE program.
