### ISSUE TITLE
Mod 3 City Verification and Approval Contribution Stories

### ISSUE THREAD

**Issue by danmelton** [hackoregon/openelections#613]
Add your name to the brackets and then self-assign the story. When you start working on it, post in our slack chat room. When you finish it, assign dan as a reviewer on  your PR.

- [] Add route for get /matches/:id to api and frontend ducks - https://github.com/hackoregon/openelections/issues/614
- [] Add route for put /matches/:id - https://github.com/hackoregon/openelections/issues/615
- []  Match Widget - https://github.com/hackoregon/openelections/issues/612
- [] View all contributions with filters - https://github.com/hackoregon/openelections/issues/617
- [] Add match contribution to status drop down and trigger modal - to https://github.com/hackoregon/openelections/issues/620
- [] Add previous donations to contributions/:id - https://github.com/hackoregon/openelections/issues/619
- [] Update the status of a contribution https://github.com/hackoregon/openelections/issues/621
