### ISSUE TITLE
Add xml tests

### ISSUE THREAD

**Issue by andrewbiang888** [hackoregon/openelections#902]
### What

From #284 the following task was defined:
- [ ] Your first task is to pull all the schemas out of that [document](https://sos.oregon.gov/elections/Documents/xml_specs.pdf), and consolidate into the top level items. I imagine there will be one for a `contact` and a `transaction`. There might be more. Create a schemas folder in the `api/test/schemas`, and place each one in there. You should attempt to validate the schemas as you go, using an online schema validator and [seth's campaign finance data](http://swoolley.org/files/s4pm-actblue.xml) link.

This issue goes more in depth into this task and will likely need to be expanded upon.

### Why

These tests will be used to verify xml schema.

### Subtasks

- [ ] Create a `contact.ts` file in `api/test/schemas` directory that contains the contact xml schema.
- [ ] Create a `transaction.ts` file in `api/test/schemas` directory that contains the transaction xml schema.

**Comment by andrewbiang888** [comment]
Put all in /schemas since they will be used on both contributions and transactions
