### ISSUE TITLE
Create json-to-xml converter with tests

### ISSUE THREAD

**Issue by andrewbiang888** [hackoregon/openelections#903]
### What
In #284 the following task was defined:
- [ ] create a conversion utility that converts a contribution or expenditure into the schema for a contact or a transaction. This should go into `models/utils/ModelNameConverter.ts`. Write a corresponding test for each file in `test/converters/`. Create one for a Contact, Contribution, and Expenditure.

### Subtasks
- [x] Create a json-to-xml converter utility
- [x] Create tests for Contact
- [x] Create tests for Contribution
- [x] Create tests for Expenditure
